name = "DrawDefine"
uuid = "094f0b2f-4d53-4957-b3e5-4a9cb0e2e947"
authors = ["Cris Moen <54078289+cristophermoen@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
